version: "3.9"

services:
  app:
    build: .
    environment:
      - FLASK_ENV=prod
    ports:
      - "5000:5000"
    volumes:
      - instance:/home/workspace/cits5505/instance

volumes:
  instance:
